mudge/re2

.travis.yml
README.md
ext/re2/extconf.rb
ext/re2/re2.cc

As raised by @stefanor, recent versions of re2 now require a compiler with C++11 support and this gem will fail to compile without the appropriate build flags.
Attempt to detect newer versions and try potential build flags to successfully compile the gem regardless of re2 version.
This also includes a workaround for a bug in Ruby 2.3.0 (fixed in 2.3.1) where memset_s is not included in string.h when using C++11 by requiring Ruby's headers before loading re2.

Support versions of re2 that require C++11

---

.travis.yml
Gemfile.lock
ext/re2/extconf.rb

GitHub: https://github.com/mudge/re2/issues/33
Follow the lead from Nokogiri and the sqlite3 gem by using the CC (and CXX) environments to configure the Makefile during installation if present.
See:
* https://github.com/sparklemotion/sqlite3-ruby/blob/master/ext/sqlite3/extconf.rb#L7
* https://github.com/sparklemotion/nokogiri/blob/master/ext/nokogiri/extconf.rb#L395-L402

Use CC and CXX from the environment

---

ext/re2/extconf.rb

GitHub: https://github.com/mudge/re2/issues/33
When compiling the gem with a compiler specified through the CC and CXX environment variables, we need to update both the Makefile configuration and standard Ruby configuration so that the various pre-compilation checks and final Makefile use the right compiler toolchain.
This should hopefully allow compilation on OpenBSD using egcc and eg++ (tested in VirtualBox).

Use environment CC and CXX throughout compilation

---

.travis.yml

As Dropbox have changed their public download URLs and I have migrated away from it personally, switch to using GitHub release assets for storing the pre-built versions of re2 needed on Travis CI.

Use re2 versions from GitHub releases in CI

---

ext/re2/re2.cc

GitHub: https://github.com/mudge/re2/issues/40
As re2 has [deprecated][0] and now [removed][1] the utf8 option, re-implement the option in the gem in terms of the encoding and set_encoding API.
This should be entirely backward-compatible as the encoding API has been present since the initial release in 2010.
Thanks to @buzzdeee for reporting this upcoming breaking change.
[0]: https://github.com/google/re2/commit/58141dc9c92189ed8d046f494f5e034d5db91bea#diff-6dc69df7618951357bb5fb674c66aa34R640
[1]: https://github.com/google/re2/commit/ac65d4531798ffc9bf807d1f7c09efb0eec70480#diff-6dc69df7618951357bb5fb674c66aa34L640-L649

Stop using the deprecated utf8 API on RE2::Options

---

.github/workflows/tests.yml

Use [GitHub's cache action](https://github.com/actions/cache) to cache Ruby dependencies for legacy Rubies. This is done automatically by the setup-ruby action for more recent Ruby versions but we do it manually for Ruby < 2.1.

Cache Ruby dependencies for legacy Rubies in CI

---

README.md
ext/re2/extconf.rb

GitHub: https://github.com/mudge/re2/issues/50
To make installation easier for users of Homebrew on Apple Silicon, add /opt/homebrew to the default paths searched when trying to find the underlying re2 library.  While doing so, add an extra fallback to /usr (instead of only searching /usr/local).
Note we still search /usr/local first to avoid accidentally changing behaviour for existing users (e.g. suddenly compiling against a different version of re2 in /usr).

Search Homebrew's prefix on Apple Silicon

---

ext/re2/re2.cc
spec/re2/regexp_spec.rb
spec/re2/scanner_spec.rb

As re2 will report the number of capturing groups for an invalid regular expression as -1, we need to check whether a pattern is OK or not before using the number to initialize any vectors, etc.
This was causing a crash when using `RE2::Scanner#scan` with an invalid regular expression as we would attempt to initialize vectors with a length of -1. Instead, set the number of capturing groups to 0 and rely on re2's `FindAndConsumeN` returning false so we return nil to the user to indicate no match was made.
Following that, ensure we always check a pattern is OK before using its number of capturing groups as a positive integer.
This also fixes an edge case in `RE2::Regexp#match` when a user passes a negative number for the number of intended matches. Previously, this would throw a misleading …

Fix crash when using RE2::Scanner#scan with an invalid regular expression

---

ext/re2/re2.cc
spec/re2/match_data_spec.rb

GitHub: https://github.com/mudge/re2/issues/57
In order to support pattern matching `RE2::MatchData` objects, implement:
* `RE2::MatchData#deconstruct`
* `RE2::MatchData#deconstruct_keys`

Support pattern matching

---

.github/workflows/tests.yml
README.md
ext/re2/re2.cc
lib/re2/string.rb
spec/re2/regexp_spec.rb

Note Ruby 3.2 will remove the Fixnum constant altogether (having been unified into Integer and deprecated previously) so prefer Integer instead.

Test Ruby 3.2.0-rc1 support

---

.github/workflows/tests.yml
Rakefile
dependencies.yml
ext/re2/extconf.rb
lib/re2.rb
re2.gemspec

This pull request:
* Vendors re2 and abseil in the Ruby platform gem.
* Builds precompiled native gems for the following platforms:
- aarch64-linux
- arm-linux
- arm64-darwin
- x64-mingw-ucrt
- x86-linux
-  x86-mingw32
- x86_64-darwin
- x86_64-linux
* By default, build and link against the vendored re2 and abseil versions. `cmake` and a C++17 compiler is required for this to work. Users can specify `--enable-system-libraries` or set `RE2_USE_SYSTEM_LIBRARIES`.
This makes it possible to ensure all the required dependencies are contained within the C extension rather than depend on system libraries, which may break the extension when they are updated.
The building of these libraries uses mini_portile2 and techniques borrowed from the nokogiri and ruby-magic gems.
glibc 2.29 is required for …

Vendor re2 and abseil

---

.github/workflows/tests.yml
ext/re2/extconf.rb
re2.gemspec

Older versions of Ruby have reached end-of-life. Shipping precompiled gems means that we have to include libraries for all supported versions.
Closes #68

Require Ruby 2.7

---

Rakefile
ext/re2/extconf.rb
re2.gemspec

This fixes a number of build issues found in https://github.com/mudge/re2/pull/76.

Fix build issues for vendored gems

---

.github/workflows/precompiled.yml
Rakefile
ext/re2/extconf.rb
lib/re2.rb
lib/re2/version.rb
re2.gemspec
scripts/test-gem-build
scripts/test-gem-install

This ensures that all precompiled gems are built properly and can be run on their target operating systems.
In addition, this ensures the Ruby platform gem can be installed and tested on all platforms.
This also fixes a number of build and install issues on Windows, such as https://github.com/pkgconf/pkgconf/issues/268.
Closes #69 and #70

Add round-trip tests for precompiled gems

---

.github/workflows/precompiled.yml

The script for installing the package did not actually execute because `pwsh` was loaded instead of `bash`.
As of today, the rake-compiler-dock image for:
1. `mri-x64-mingw-ucrt` only supports Ruby 3.1 and 3.2.
2. `mri-x64-mingw32` only supports Ruby 2.4 - 3.0.

Fix Windows gem tests

---

.github/workflows/precompiled.yml
ext/re2/extconf.rb

Due to https://github.com/pkgconf/pkgconf/issues/268, we manually worked around Windows link order issues by adding abseil libraries manually. However, a few libraries were missed from that list, which are added only in Windows builds:
* dbghelp
* advapi32
This commit adds these libraries to the right location, which fixes `x86-mingw32` builds.
Note there is an existing issue with abseil including `-ldbghelp` before `-labsl_symbolize`, which this commit corrects: https://github.com/abseil/abseil-cpp/issues/1497

Fix a few misordered Windows libraries

---

ext/re2/extconf.rb

Previously if you ran:
```shell
bundle exec rake gem:x64-mingw-ucrt
bundle exec rake gem:x64-mingw32
```
The latter would fail with undefined symbols:
```shell
linking shared-object re2.so
/usr/bin/x86_64-w64-mingw32-ld: /tmp/re2/ports/x86_64-w64-mingw32/abseil/20230125.3/lib/libabsl_time_zone.a(time_zone_libc.cc.obj):time_zone_libc.cc:(.text+0x97): undefined reference to `__imp___timezone'
/usr/bin/x86_64-w64-mingw32-ld: /tmp/re2/ports/x86_64-w64-mingw32/abseil/20230125.3/lib/libabsl_time_zone.a(time_zone_libc.cc.obj):time_zone_libc.cc:(.text+0xa8): undefined reference to `__imp___dstbias'
/usr/bin/x86_64-w64-mingw32-ld: /tmp/re2/ports/x86_64-w64-mingw32/abseil/20230125.3/lib/libabsl_time_zone.a(time_zone_libc.cc.obj):time_zone_libc.cc:(.text+0xde): undefined reference to …
```

Ensure different Windows flavors build their own abseil library

---

.github/workflows/precompiled.yml

This will allow more time to inspect and download precompiled gems.
Also update GitHub Action steps to the latest versions.

Increase artifact retention time to 7 days

---

Rakefile
ext/re2/extconf.rb
ext/re2/recipes.rb
re2.gemspec
scripts/test-gem-build

Previously `scripts/test-gem-build` would call `rake compile` just to make mini_portile2 download the source tarballs. However, this needlessly compiles abseil and libre2 before building the gem.
To improve this, split the loading of the recipes into a separate file (`ext/re2/recipes.rb`). The `rake prepare` step invokes the `download` method to download the required tarballs in preparation for building the gem.
Now we add a `rake prepare` task that will run if `rake gem` is run.

Make `rake gem` download source tarballs automatically

---

.github/workflows/tests.yml
scripts/test-gem-install

This would better reflect how users might install the gem.

Update the system dependency tests to use the built gem

---

.github/workflows/tests.yml
lib/re2/version.rb
scripts/test-gem-build

Only call `rake set-version-to-timestamp` if we're on a branch. This will make it possible to build precompiled gems with the right version tag.

Bump version to v2.0.0.beta1

---

.github/workflows/tests.yml
ext/re2/extconf.rb

Ruby's mkmf appears to list `RbConfig::CONFIG['exec_prefix']/lib` first in the search path when building a C extension. If you have libre2 installed in that path, the linker will use that library instead of the vendored library. This causes an undefined symbol error when using the extension:
```shell
/usr/local/bin/ruby: symbol lookup error: /usr/local/bundle/gems/re2-2.0.0.beta1/lib/re2.so: undefined symbol: _ZN3re23RE2C1ESt17basic_string_viewIcSt11char_traitsIcEERKNS0_7OptionsE
```
This commit does two things to ensure the final shared library is compiled statically with the vendored libraries:
1. For `-L<path>` flags, ensure that any `ports` paths are prioritized just in case there are installed libraries that might take precedence.
2. For `-l<lib>` flags, convert the library to the …

Fix static linking when system libraries installed

---

README.md
dependencies.yml

Note we're not also upgrading abseil to its latest version (20230802.0) as it drops compatibility for macOS 10.13 and requires workarounds on Windows (see https://github.com/abseil/abseil-cpp/issues/1510).
(See https://github.com/mudge/re2/pull/95 for a PR to also upgrade abseil.)

Upgrade RE2 to 2023-09-01

---

.github/workflows/tests.yml
Rakefile
ext/re2/extconf.rb
re2.gemspec

As the default system Ruby on macOS Monterey is 2.6 and MiniPortile2 supports back to 2.3, restore support for that Ruby and compile the C extension for it in the native gems.
The trade-off here is that we increase the size of the native gem in order to support more Ruby versions. While 2.6 is technically EOL, the rubygems.org stats still show usage of it in the past month: https://ui.honeycomb.io/ruby-together/datasets/rubygems.org/result/HBSqTboW1yi
Note Ruby 2.6 triggers a register error with C++17 (it was fixed by https://github.com/ruby/ruby/commit/113bef697633803a33a547914b16ba5fbef165b8 in Ruby 2.7) so we disable that particular error during compilation.

Add Ruby 2.6 support for native gems

---

.yardopts
LICENSE-DEPENDENCIES.txt
LICENSE.txt
README.md
ext/re2/re2.cc
re2.gemspec
spec/kernel_spec.rb
spec/re2/match_data_spec.rb
spec/re2/regexp_spec.rb
spec/re2/scanner_spec.rb
spec/re2/set_spec.rb
spec/re2/string_spec.rb
spec/re2_spec.rb
spec/spec_helper.rb

Where possible, coerce inputs to strings with StringValue rather than raising a TypeError. This particularly impacts the relatively recent RE2::Set API which was excessively strict about its arguments.
Add test coverage to all parts of the API, better covering edge cases including how encoding is handled based on the encoding of the RE2 pattern.

Increase test coverage, coerce inputs to string and fix encoding inconsistencies

---

ext/re2/extconf.rb
ext/re2/re2.cc

Try to address some of the items from #59 and improve the C++ code of the extension.
Namely:
- Replace use of "using" with explicit naming
- Use references to NamedCapturingGroups, not copies

Assorted C++ cleanup

---

.github/workflows/tests.yml

Try to speed up builds by reducing duplication (no longer testing the Rake extension task but only testing the gems).

Tidy up GitHub Actions

---

ext/re2/re2.cc

See https://github.com/mudge/re2/issues/104
Specifically:
* Ensure we delete the previous input inside an RE2::Scanner before replacing it
* Check whether inputs are strings as early as possible to avoid raising an exception after allocating memory
* Make sure the error string populated by RE2::Set->Add() goes out of scope before calling `rb_raise`

Fix memory leaks found by ruby_memcheck

---

ext/re2/re2.cc

As strncpy will truncate any error messages over 100 characters long without null termination, switch to using the safer strlcpy which guarantees null termination.

Prevent overflow if RE2 error strings are too long

---

.github/workflows/dependencies.yml
dependencies.yml
scripts/update-dependencies

So we can stay on top of updates to both RE2 and Abseil now they are vendored with the gem, run a monthly job to check for any new releases and update `dependencies.yml` accordingly, raising a PR if there are any.
Closes https://github.com/mudge/re2/issues/107

Add workflow to upgrade vendored dependencies

---

.github/workflows/tests.yml

Before compiling the native gems against the latest, unreleased version of Ruby, check the gem compiles and passes its tests when the user has to compile against it on install.
See https://github.com/mudge/re2/issues/108

Run compilation tests against Ruby 3.3.0-preview2

---

ext/re2/recipes.rb
re2.gemspec

This update builds abseil-cpp in Release mode
(https://github.com/flavorjones/mini_portile/pull/136). For the x86_64 shared object, it appears that this shrinks `re2.so`from 2766744 bytes to 1506992 bytes, a 45% reduction.

Upgrade mini_portile to v2.8.5

---

.gitignore
ext/re2/extconf.rb
ext/re2/re2.cc
spec/re2/match_data_spec.rb

Use the `TypedData` API introduced in Ruby 1.9.2, instead of the old `Data` API that was deprecated in Ruby 2.3.
This allows to implement Write Barriers.
Write barrier protected objects are allowed to be promoted to the old generation, which means they only get marked on major GC, making minor GC faster.
The downside is that the `RB_BJ_WRITE` macro MUST be used to set references, otherwise the referenced object may be garbaged collected.
This also allow to implement GC compaction.

Modernize usage of Ruby's C extension API

---

ext/re2/re2.cc

With g++ v7.3.1 (used with Amazon Linux 2), compiling the extension would fail with these errors:
```
compiling re2.cc
re2.cc:176:1: sorry, unimplemented: non-trivial designated initializers not
supported
};
^
re2.cc:221:1: sorry, unimplemented: non-trivial designated initializers not
supported
};
^
re2.cc:251:1: sorry, unimplemented: non-trivial designated initializers not
supported
};
^
re2.cc:1610:1: sorry, unimplemented: non-trivial designated initializers not
supported
};
^
```
This appears to be happening because the `parent` and `data` fields in `rb_data_type_struct` were omitted.
According to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=55606, this issue was fixed in GCC 8.

Fix "non-trivial designated initializers not supported" errors

---

.github/workflows/tests.yml
README.md
ext/re2/extconf.rb

The linker order problem in  abseil/abseil-cpp#1497 was shipped with abseil-cpp 20230802.0.
pkgconf v2.1.0 fixed pkgconf/pkgconf#268 and pkgconf/pkgconf#322, so we should no longer need to add the abseil linker flags manually.
Update CI to use pkgconf v2.1.0 for Windows machines and a note in README.me about using the right version.

Drop abseil-cpp build workarounds on Windows

---

.github/workflows/tests.yml
CHANGELOG.md
Rakefile
lib/re2/version.rb
re2.gemspec

Use [rake-compiler-dock 1.4.0.rc2](https://github.com/rake-compiler/rake-compiler-dock/releases/tag/1.4.0.rc2) to precompile a native gem for Ruby 3.3 and test it on all supported platforms.

Precompile native gems for Ruby 3.3.0

---

.rspec
ext/re2/re2.cc
spec/kernel_spec.rb
spec/re2/match_data_spec.rb
spec/re2/regexp_spec.rb
spec/re2/scanner_spec.rb
spec/re2/set_spec.rb
spec/re2_spec.rb

GitHub: https://github.com/mudge/re2/issues/130
Ensure that whenever we pass Ruby string data into RE2 we use the data's explicit length as returned by RSTRING_LEN rather than relying on null-termination. RSTRING_PTR doesn't guarantee this (see https://docs.ruby-lang.org/en/3.3/extension_rdoc.html#label-VALUE+type+conversion) and we can end up either truncating input or, worse, over-reading.

Support null bytes in string inputs

---

.github/workflows/tests.yml

pkgconf v2.1.1 has a regression with producing the right link order for abseil (https://github.com/pkgconf/pkgconf/issues/343). Pin the version to v2.1.0 until that is resolved.

Pin pkgconf v2.1.0

---

.github/workflows/tests.yml
ext/re2/extconf.rb
ext/re2/recipes.rb

GitHub: https://github.com/mudge/re2/issues/109
MiniPortile2 2.8.5 ships with a mkmf_config feature that can handle statically linking libraries for us, however it doesn't currently work with our use case due to Abseil shipping with over 180 separate `.pc` files. That said, we can still update how we statically link RE2 into the gem based on MiniPortile2's strategy.
We also take a leaf from the Ruby SQLite3 gem's extconf (https://github.com/sparklemotion/sqlite3-ruby/blob/ae5c13996f936fce07e8a5e9fb6aaf2ede5d82b7/ext/sqlite3/extconf.rb#L113) and re-organise the configuration logic in our extconf.rb into a class rather than a series of global functions.

Learn from MiniPortile2's mkmf_config to simplify building vendored dependencies

---

.github/workflows/tests.yml

To make the matrix for the "compile-and-test-vendored-dependencies" job a bit easier to manage, split it into separate jobs by OS.

Split CI jobs by OS

---

.github/workflows/precompile-gem.yml
.github/workflows/tests.yml

Rather than using a matrix strategy to build all precompiled gems and then test them individually, use a reusable workflow to precompile gems and test gems separately, hopefully speeding up the build.

Parallelise precompiled gems

---

.github/workflows/tests.yml

See https://github.com/flavorjones/ruby-c-extensions-explained/pull/30/commits/db36156105a9d8c30478f56de72ad44c9494736a

Use explicit versions of macOS in CI

---

.github/workflows/tests.yml
Gemfile
Rakefile

So we can catch any new memory leaks, run ruby_memcheck as part of the build.

Run ruby_memcheck in CI

---

.github/workflows/tests.yml

Now Ruby 3.4.0-preview1 is available, add it to the build matrix for Ubuntu and macOS (prerelease versions are not generally available for Windows).

Test against Ruby 3.4

---

re2.gemspec

Since RE2 2024-06-01, the CI build for x86-linux and x86_64-linux slowed from around 15 minutes to almost an hour. This turned out to be due to the rake-compiler-dock images for those platforms having pkg-config 0.27.1 which performs very slowly with RE2's .pc file compared to more recent versions. This will instead use pkg-config 0.29.2 which should take a fraction of a second compared to the minutes 0.27.1 took to execute commands such as `pkg-config --libs-only-L --static re2.pc`.
Thanks to @flavorjones for putting out a fix so promptly.

Upgrade to rake-compiler-dock 1.5.1

---

Rakefile
ext/re2/recipes.rb
patches/abseil/0001-Avoid-export-of-testonly-target-absl-test_allocator-.patch

Fixes https://github.com/mudge/re2/issues/158

Add patch to fix building Abseil with CMake 3.30.0

---

.github/workflows/tests.yml
README.md
Rakefile

Due to changes in rake-compiler-dock, running a single Linux gem for both GNU and Musl libraries no longer works reliably so precompile separate gems and drop support for older Rubies accordingly.

Split out separate GNU and Musl gems

---

.github/workflows/dependencies.yml
.github/workflows/docs.yml
.github/workflows/precompile-gem.yml
.github/workflows/tests.yml
README.md
Rakefile
re2.gemspec
scripts/test-gem-install

- **Restore Ruby 3.0 support**
- **Upgrade to rake-compiler-dock 1.7.0**

Restore Ruby 2.6, 2.7, and 3.0 support

---

.github/workflows/tests.yml
Rakefile
re2.gemspec

This avoids the need to hard-code specific patch-level versions.
See https://github.com/rake-compiler/rake-compiler-dock/releases/tag/v1.9.1.

Set RUBY_CC_VERSION using RakeCompilerDock.set_ruby_cc_version

---

.github/workflows/tests.yml

As Ruby 3.5.0-preview1 was released back in April (see https://www.ruby-lang.org/en/news/2025/04/18/ruby-3-5-0-preview1-released/), add it to the build (note prerelease versions of Ruby are not made available for Windows so we use Ruby HEAD instead).

Test against Ruby 3.5 preview versions

---

.github/workflows/tests.yml
CHANGELOG.md
README.md
Rakefile
ext/re2/extconf.rb
ext/re2/re2.cc
re2.gemspec
scripts/test-gem-install

Based on the logs from rubygems.org in the past 60 days, Ruby versions older than 3.1 account for less than 0.2% of downloads. See https://ui.honeycomb.io/ruby-together/datasets/rubygems.org/result/ms4mhTPGhaJ?vs=hideCompare&cstype_0=tsbar&tab=overview
I've long kept support for old versions even if they were considered end-of-life but only under the assumption people were still actively using those versions in production. Given the rubygems.org stats and similar version support from the likes of much more popular projects such as Nokogiri, let's finally drop support and simplify maintenance.

Drop support for Ruby versions older than 3.1
